### PR TITLE
Several small fixes

### LINKED ISSUE #17471: An error appears when starting a workspace with the OpenShift-connector plugin
### Describe the bug

An error appears when starting a workspace with the openshift-connector plugin
### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Create a workspace
2. Apply the `openshift-connector` plugin
3. See the error:
screenshot-che openshift io-2020 07 23-15_22_18

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [x] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### PR DESCRIPTION
**Pull request by vinokurig**
- Fix an error with axios dependency
- Skip the authentication if the login state is restored
- Do not pass cerificate to the login command if Hosted Che
- Update `yarn.lock` file

fixes https://github.com/eclipse/che/issues/17471

### CODE REVIEW

File: src/che-openshift-authentication.ts [hunk 1]
```diff
@@ -84,7 +87,11 @@ export async function start(context: theia.PluginContext) {
             theia.window.showErrorMessage(errorMessage + e);
             return;
         }
-        const osCommand = spawn('oc', ['login', server, '--certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt', '--token', token]);
+        const args = ['login', server, '--token', token];
+        if (!isHostedChe) {
+            args.push('--certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt');
```
Comment (vitaliy-guliy) [inline src/che-openshift-authentication.ts:92]: Could you extract the path to a constant? Just for paying attention on it, if the path is not changed.

**Review by vitaliy-guliy — APPROVED** [review]

File: src/che-openshift-authentication.ts (hunk 1 above)
Comment (vinokurig) [reply src/che-openshift-authentication.ts:92]: I prefer to keep it inline, this path is used only in a single place.

**Review by ericwill — APPROVED** [review]
LGTM
